FROM openjdk:17
LABEL maintainer="springBootCRUDOperation"
ADD target/springBootCRUDOperation-0.0.1-SNAPSHOT.jar springBootCRUDOperation.jar
ENTRYPOINT ["java","-jar","springBootCRUDOperation.jar"]